### ISSUE TITLE
ImportError: cannot import name 'default_rng'

### ISSUE THREAD

**Issue by jym0404** [dfpena/epidemic-simulation-pygame#1]
I downloaded this program and I ran it.
but it showed me an Import error. Like this 
ImportError: cannot import name 'default_rng'
I installed numpy, but it still showed me an Import error.
I can't fix it.

**Comment by dfpena** [comment]
Upgrade your numpy install and try again

**Comment by dfpena** [comment]
If that doesnt work I'll update to remove that import.

**Comment by dfpena** [comment]
Removed the dependency it should work now

**Comment by jym0404** [comment]
I installed numpy again and again.

**Comment by jym0404** [comment]
Thank you so much!
